import { compileFromFile } from "json-schema-to-typescript";

import fs from "fs";
import glob from "glob";
import path from "path";

const base_dir = path.resolve(__dirname, "../../../apps");

// https://jsontypedef.com/
const files = glob.sync(base_dir + "/**/schemas/*.json");

const options = {
    "bannerComment": "/**\n* This file was automatically generated by source/platform/system/schemas/json2ts.ts\n* DO NOT MODIFY IT MANUALLY. Instead, modify the source JSON Schema file,\n* and run 'npm run schemas' to regenerate this file.\n* The source file has the same name as this one but has the extension .json\n*/"
};

for (const file of files) {

    console.log(`Converting file: ${file}`);

    const ts_file = file.replace(".json", ".ts");

    compileFromFile(file, options).then(ts_text => fs.writeFileSync(ts_file, ts_text));

}