#!/bin/sh

echo "---------------------"
echo "Running pre-push hook"
echo "---------------------"

. .env/local

if output=$(git status --porcelain) && [ -z "$output" ]; then
    echo "--------------------"
    echo "End of pre-push hook"
    echo "--------------------"
    exit 0
else
    echo "------------------"
    echo "Uncommited changes"
    echo "------------------"
    exit 1
fi