/**
 * This file was automatically generated by source/platform/system/schemas/json2ts.ts
 * DO NOT MODIFY IT MANUALLY. Instead, modify the source JSON Schema file,
 * and run 'npm run schemas' to regenerate this file.
 * The source file has the same name as this one but has the extension .json
 */

export interface ZombiInfraSystemPublicUserData {
  id: string;
  username: string;
  fullname: string;
  email: string;
  password: string;
  timezone: string;
  country: string;
  language: string;
  enabled: string;
  created_by: string;
  created_ts: number;
  password_recovery_token?: string | null;
  password_recovery_ts: number | null;
}
