name: Zombi CI Actions Development

on:
  push:
    branches:
      - "*"
      # - "!master"

env:
  CI: true
  EXCHANGE_OMS_ID: 1
  ISOLATE: true

jobs:
  testing_job:
    environment: local
    # if: ${{ false }}
    runs-on: ubuntu-20.04
    env:
      ZOMBI_ENV: ${{ secrets.LOCAL_ENV }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres:14
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$ZOMBI_ENV" > ".env/local"
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm i
      - name: Run tests
        run: . .env/local ; npm run test
  deploy_job:
    environment: development
    # if: ${{ false }}
    needs: testing_job
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm i
      - name: "Stablish SSH tunnel to DB via bastion host"
        # run: echo "${{ secrets.BASTION_SSH_KEY }}" | tr -d '\r' > key.pem; chmod 400 key.pem
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{secrets.BASTION_HOST}} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{secrets.BASTION_SSH_KEY}}"
          ssh -fN -v -L 5432:${{secrets.DB_HOST}}:5432 ec2_user@${{secrets.BASTION_HOST}}
      - name: "Run DB migrations"
        # run: ssh -i ec2-key-dev.pem ec2-user@ec2-3-91-34-224.compute-1.amazonaws.com -C 'export ZOMBI_DB_URL="${{ secrets.ZOMBI_DB_URL }}"; rm -rf zombi-backend; git clone https://github.com/${{github.repository}}.git ; cd zombi-backend/migrations/; sudo -E ./migrations.sh migrate'
        run: |
          cd migrations
          sudo -E ./migrations.sh migrate
      - name: Deploying code for lambdas
        run: bash ./deploy.sh
