name: Zombi CI Actions Development

on:
  push:
    branches:
      - "*"
      - "!master"

env:
  CI: true
  EXCHANGE_OMS_ID: 1
  ISOLATE: true

jobs:
  testing_job:
    # if: ${{ false }}
    runs-on: ubuntu-20.04
    env:
      ZOMBI_ENV: ${{ secrets.LOCAL_ENV }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$ZOMBI_ENV" > ".env/local"
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm i
      - name: Run tests
        run: . .env/local ; npm run test
  deploy_job:
    # if: ${{ false }}
    needs: testing_job
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm i
      - name: Deploying code for lambda MICROSERVER
        run: bash ./deploy.sh
