name: Zombi CI Actions Development
on:
  push:
    branches:
      - "*"
      # - "!master"
env:
  CI: true
  EXCHANGE_OMS_ID: 1
  ISOLATE: true
jobs:
  testing_job:
    runs-on: ubuntu-20.04
    env:
      LOCAL_ENV: ${{ secrets.LOCAL_ENV }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$LOCAL_ENV" > ".env/local"
      - name: Install dependencies
        run: npm i
      - name: "Run DB migrations"
        run: |
          . .env/local
          cd migrations
          sudo -E ./migrations.sh migrate
          cd ..
      - name: Run linter
        run: . .env/local ; npm run lint
      - name: Run tests
        run: . .env/local ; npm run test
  deploy_job:
    needs: testing_job
    runs-on: ubuntu-20.04
    env:
      DEVELOPMENT_ENV: ${{ secrets.DEVELOPMENT_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$DEVELOPMENT_ENV" > ".env/development"
      - name: Install dependencies
        run: npm i
      - name: "Create SSH key from secret"
        run: |
          . .env/development
          mkdir ~/.ssh
          ssh-keyscan -H ${BASTION_HOST} >> ~/.ssh/known_hosts
          echo "${BASTION_SSH_KEY}" > ssh_key
          chmod 600 ./ssh_key
      - name: "Run DB migrations"
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        # run: . .env/development ; ssh -i ./ssh_key ec2-user@${BASTION_HOST} -C 'export ZOMBI_DB_URL="${ZOMBI_DB_URL}"; cd /tmp ; rm -rf zombi-backend; git clone --branch ${{ env.BRANCH_NAME }} https://github.com/${{ github.repository }}.git ; cd zombi-backend/migrations/; sudo -E ./migrations.sh migrate ; rm -rf zombi-backend'
        run: . .env/development ; ssh -i ./ssh_key ec2-user@${BASTION_HOST} -C 'export ZOMBI_DB_URL="${ZOMBI_DB_URL}"; cd /tmp ; rm -rf ${{ github.repository }}; git clone --branch ${{ env.BRANCH_NAME }} https://github.com/${{ github.repository }}.git ; cd ${{ github.repository }}/migrations/; sudo -E ./migrations.sh migrate ; rm -rf ${{ github.repository }}'
      - name: Deploying code for lambdas
        run: . .env/development ; bash ./deploy.sh
