name: Zombi CI Actions Production (Deploy)
on:
  pull_request:
    branches:
      - master
jobs:
  testing_job:
    environment: local
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    env:
      LOCAL_ENV: ${{ secrets.LOCAL_ENV }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$LOCAL_ENV" > ".env/local"
      - name: Install dependencies
        run: npm i
      - name: "Run DB migrations"
        run: |
          . .env/local
          cd migrations
          sudo -E ./migrations.sh migrate
          cd ..
      - name: Run tests
        run: . .env/local ; npm run test
  deploy_job:
    environment: production
    if: github.event.pull_request.merged == true
    needs: testing_job
    runs-on: ubuntu-20.04
    env:
      PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Creates the environment file
        run: mkdir .env ; printf "%s" "$PRODUCTION_ENV" > ".env/development"
      - name: Install dependencies
        run: npm i
      - name: "Create SSH key from secret"
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.BASTION_SSH_KEY }}" > ssh_key
          chmod 600 ./ssh_key
      - name: "Setting ZOMBI_DB_URL env"
        run: . .env/development ; echo "ZOMBI_DB_URL=${ZOMBI_DB_URL}" ; echo "ZOMBI_DB_URL=${ZOMBI_DB_URL}" >> $GITHUB_ENV
      - name: "Run DB migrations"
        run: . .env/development ; ssh -i ./ssh_key ec2-user@${{ secrets.BASTION_HOST }} -C 'export ZOMBI_DB_URL="${{ env.ZOMBI_DB_URL }}"; rm -rf zombi-backend; git clone https://github.com/${{github.repository}}.git ; cd zombi-backend/migrations/; sudo -E ./migrations.sh migrate'
      - name: Deploying code for lambdas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: . .env/development ; bash ./deploy.sh
